### ISSUE TITLE
Buildout does not work for Odoo 13.0

### ISSUE THREAD

**Issue by NL66278** [anybox/anybox.recipe.odoo#126]
```
anybox.recipe.odoo.base: Creating config file: etc/odoo.cfg
While:
  Installing odoo.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/openeyedev/var/projects/odoo13_13001/eggs/anybox.recipe.odoo-1.9.3.dev0-py3.6.egg/anybox/recipe/odoo/server.py", line 107, in _create_default_config
    from odoo.tools.config import configmanager
  File "/home/openeyedev/var/projects/odoo13_13001/parts/odoo/odoo/__init__.py", line 117, in <module>
    from . import service
  File "/home/openeyedev/var/projects/odoo13_13001/parts/odoo/odoo/service/__init__.py", line 7, in <module>
    from . import wsgi_server
  File "/home/openeyedev/var/projects/odoo13_13001/parts/odoo/odoo/service/wsgi_server.py", line 25, in <module>
    import werkzeug.contrib.fixers
ModuleNotFoundError: No module named 'werkzeug.contrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/openeyedev/var/projects/odoo13_13001/eggs/zc.buildout-2.13.2-py3.6.egg/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/home/openeyedev/var/projects/odoo13_13001/eggs/zc.buildout-2.13.2-py3.6.egg/zc/buildout/buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/openeyedev/var/projects/odoo13_13001/eggs/zc.buildout-2.13.2-py3.6.egg/zc/buildout/buildout.py", line 1603, in _call
    return f()
  File "/home/openeyedev/var/projects/odoo13_13001/eggs/anybox.recipe.odoo-1.9.3.dev0-py3.6.egg/anybox/recipe/odoo/base.py", line 1148, in install
    self._create_default_config()
  File "/home/openeyedev/var/projects/odoo13_13001/eggs/anybox.recipe.odoo-1.9.3.dev0-py3.6.egg/anybox/recipe/odoo/server.py", line 109, in _create_default_config
    from openerp.tools.config import configmanager
ModuleNotFoundError: No module named 'openerp'
```

**Comment by NL66278** [comment]
Is this the same as this one? https://github.com/anybox/anybox.recipe.odoo/issues/113

**Comment by StefanRijnhart** [comment]
Can't reproduce. Can you debug and come back with the full ImportError raised in line 107 of that file?

**Comment by NL66278** [comment]
It seems to be due to an update in Werkzeug. Pinning this to 0.16.1 will work.

**Comment by StefanRijnhart** [comment]
Thanks for the feedback
