### ISSUE TITLE
python_odoo is failing with "DeprecationWarning: Since Odoo 15.0, Environment.manage() is useless." on Odoo 15.0

### ISSUE THREAD

**Issue by cmsalmeida** [anybox/anybox.recipe.odoo#138]
Running session.open(<DATABASE>) in python_odoo for Odoo 15.0, we get the following error:

2022-06-20 09:13:16,087 2066 WARNING <DATABASE> py.warnings: /opt/odoo/src/anybox-recipe-odoo/anybox/recipe/odoo/runtime/session.py:225: DeprecationWarning: Since Odoo 15.0, Environment.manage() is useless.
  File "/opt/odoo/bin/python_odoo", line 131, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "test.py", line 1, in <module>
    session.open('globalcharging.v150.mylocal.com')
  File "/opt/odoo/src/anybox-recipe-odoo/anybox/recipe/odoo/runtime/session.py", line 197, in open
    self.init_environments()
  File "/opt/odoo/src/anybox-recipe-odoo/anybox/recipe/odoo/runtime/session.py", line 225, in init_environments
    next(self._environments_gen_context)
 
Traceback (most recent call last):
  File "/opt/odoo/bin/python_odoo", line 131, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "test.py", line 2, in <module>
    print('%s' % session['res.partner'].search([]).mapped('name'))
TypeError: 'Session' object is not subscriptable

Any prediction to have this running with Odoo15.0?

**Comment by StefanRijnhart** [comment]
Hi @cmsalmeida, we have been quitely moving to https://github.com/OCA/oca.recipe.odoo. The deprecation warning "Since Odoo 15.0, Environment.manage() is useless" has been fixed in that version. But even using `anybox.recipe.odoo` you should be able to fetch the model with `session.env['res.partner']` rather than with `session['res.partner']`.
