### ISSUE TITLE
gp.vcsdevelop freeze not compatible with pip 7.1

### ISSUE THREAD

**Issue by gracinet** [anybox/anybox.recipe.odoo#47]
This is fortunately catched by unit tests, with several errors like this one:

```
======================================================================
ERROR: test_prepare_frozen_buildout_gp_vcsdevelop (anybox.recipe.odoo.tests.test_freeze.TestFreeze)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gracinet/odoo/recipe/a.r.odoo/anybox/recipe/odoo/tests/test_freeze.py", line 145, in test_prepare_frozen_buildout_gp_vcsdevelop
    self.recipe._prepare_frozen_buildout(conf)
  File "/home/gracinet/odoo/recipe/a.r.odoo/anybox/recipe/odoo/base.py", line 1166, in _prepare_frozen_buildout
    for raw, _, _, abs_path in self._get_gp_vcs_develops():
  File "/home/gracinet/odoo/recipe/a.r.odoo/anybox/recipe/odoo/base.py", line 1152, in _get_gp_vcs_develops
    parsed = pip.req.parse_editable(raw)
AttributeError: 'module' object has no attribute 'parse_editable'
-------------------- >> begin captured logging << --------------------
anybox.recipe.odoo.base: INFO: Created downloads/ directory
anybox.recipe.odoo.base: INFO: Created etc/ directory
--------------------- >> end captured logging << ---------------------
```

**Comment by gracinet** [comment]
So we still have a red build, but that's a consequence of #47, and maybe some related complication (requiring pip >=1.5.6 got us 7.1), I'll pin to 1.5.6 just to see if that's the only problem.

**Comment by gracinet** [comment]
We also had that requiring explicitely pip put it in a subdir with --upgrade (exactly as setuptools before that) and in turn adding the path to pip does not provide the recipe itself, nor its dependency.
Fixed that directly in master branch by listing all deps
