### ISSUE TITLE
TypeError: must be type, not classobj when running buildout

### ISSUE THREAD

**Issue by eLBati** [anybox/anybox.recipe.odoo#67]
Today, trying to run a "yesterday working" buildout, I get
```
$ bin/buildout 
Found command 'git' at '/usr/bin/git'
https://github.com/anybox/anybox.recipe.odoo
Clone in ./a.r.openerp exists, and has correct URL (https://github.com/anybox/anybox.recipe.odoo)
Updating ./a.r.openerp clone (to a.r.openerp-1.9)
a.r.odoo-1.9.0
a.r.openerp-1.9.0
4c8c77685a5559506068a6dcb8e84b22470bfef9
61f7822e011406185b794c6635f82010f535d774
  origin/HEAD -> origin/master
  origin/a.r.openerp-1.8
  origin/a.r.openerp-1.9
  origin/master
8eb92a1d6b031ec411959fcab333d9b4222faf25
f269a33d2342c97d9fc8b9ea6b6e001b100dd479
456605a9cf49813f0fa44f7183e8f45e952343a2
8eb92a1d6b031ec411959fcab333d9b4222faf25
Develop: '/home/elbati/workspace/odoo/progetti/agilebg/git/agilebg/a.r.openerp'
Traceback (most recent call last):
  File "/tmp/tmpTrNHJK", line 14, in <module>
    exec(compile(f.read(), '/home/elbati/workspace/odoo/progetti/agilebg/git/agilebg/a.r.openerp/setup.py', 'exec'))
  File "/home/elbati/workspace/odoo/progetti/agilebg/git/agilebg/a.r.openerp/setup.py", line 51, in <module>
    'bzr' : ['bzr'] },
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-i686/egg/setuptools/command/develop.py", line 32, in run
  File "build/bdist.linux-i686/egg/setuptools/command/develop.py", line 132, in install_for_development
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 695, in process_distribution
  File "build/bdist.linux-i686/egg/setuptools/command/develop.py", line 160, in install_egg_scripts
  File "build/bdist.linux-i686/egg/setuptools/command/develop.py", line 173, in install_wrapper_scripts
TypeError: must be type, not classobj
While:
  Installing.
  Processing develop directory '/home/elbati/workspace/odoo/progetti/agilebg/git/agilebg/a.r.openerp'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/elbati/workspace/odoo/progetti/agilebg/git/agilebg/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/home/elbati/workspace/odoo/progetti/agilebg/git/agilebg/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 528, in install
    installed_develop_eggs = self._develop()
  File "/home/elbati/workspace/odoo/progetti/agilebg/git/agilebg/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 770, in _develop
    zc.buildout.easy_install.develop(setup, dest)
  File "/home/elbati/workspace/odoo/progetti/agilebg/git/agilebg/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/easy_install.py", line 1020, in develop
    call_subprocess(args)
  File "/home/elbati/workspace/odoo/progetti/agilebg/git/agilebg/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/easy_install.py", line 160, in call_subprocess
    % repr(args)[1:-1])
Exception: Failed to run command:
'/home/elbati/workspace/odoo/progetti/agilebg/git/agilebg/sandbox/bin/python', '/tmp/tmpTrNHJK', '-q', 'develop', '-mN', '-d', '/home/elbati/workspace/odoo/progetti/agilebg/git/agilebg/develop-eggs/tmpoQ_V6dbuild'
```
The environment is created like described at http://pythonhosted.org/anybox.recipe.odoo/first_steps.html#bootstrapping-the-buildout and I am using ```a.r.openerp-1.9``` version of the recipe

Does anybody know what caused it or how to investigate it?

Thanks

**Comment by florentx** [comment]
I can confirm the issue. It happened on our CI server too.

It's related to release 18.6 of setuptools.
I've reverted to 18.5 and it works:
```bash
$ pip install setuptools==18.5
$ bin/buildout
```

**Comment by florentx** [comment]
Found upstream issue... waiting for a setuptools fix, I guess.

https://bitbucket.org/pypa/setuptools/issues/464/typeerror

**Comment by gracinet** [comment]
Thanks for report and investigation, guys.
Indeed the issue seems to be more general than in the zc.buildout
context, therefore we can hope it will be solved soon.

**Comment by StefanRijnhart** [comment]
Thanks for the pointers! Buildouts running again for now with
```
python bootstrap.py --setuptools-version 18.5
```
and 
```
[version]
setuptools=18.5
```
or 
```
[buildout]
newest=false
```

**Comment by florentx** [comment]
.... or
```ini
[version]
; Setuptools 18.6 is broken
setuptools = >=18.5,!=18.6
```

**Comment by eLBati** [comment]
Fixed with https://bitbucket.org/pypa/setuptools/pull-requests/161/issue-464-dont-crash-using-super-on-a-old/diff
Thanks!
