### ISSUE TITLE
unit test failled on buildbot9 under wheezy

### ISSUE THREAD

**Issue by petrus-v** [anybox/anybox.recipe.odoo#72]
Currently Anybox is migrate to buildbot 9 (public access is not yet available)

I wonder if there is a matter with the setting of our worker(slave) or a real issue. I open an issue to let some analysis:

Test failled on wheezy with:
```
xcpubslave:~/buildbot.anybox.fr/a_r_odoo-py2_7/build$ bin/pip --version
pip 1.1 from /srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/lib/python2.7/site-packages/pip-1.1-py2.7.egg (python 2.7)
```
and passed on Jessie with:
```
jessiepubslave:~/buildbot.anybox.fr/a_r_odoo-py2_7/build$ bin/pip --version
pip 1.5.6 from /srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/local/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg (python 2.7)
```
log output:
```
======================================================================
1769ERROR: test_prepare_extracted_buildout_gp_vcsdevelop (anybox.recipe.odoo.tests.test_extract.TestExtraction)
1770----------------------------------------------------------------------
1771Traceback (most recent call last):
1772  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/tests/test_extract.py", line 91, in test_prepare_extracted_buildout_gp_vcsdevelop
1773    self.recipe._prepare_extracted_buildout(conf, self.extract_target_dir)
1774  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1446, in _prepare_extracted_buildout
1775    for raw, target, sub_dir, abs_path in self._get_gp_vcs_develops():
1776  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1165, in _get_gp_vcs_develops
1777    target = parse_egg_dir(raw)
1778  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1161, in parse_egg_dir
1779    return ireq.editable_options['egg']
1780AttributeError: 'InstallRequirement' object has no attribute 'editable_options'
1781-------------------- >> begin captured logging << --------------------
1782anybox.recipe.odoo.base: INFO: Created downloads/ directory
1783anybox.recipe.odoo.base: INFO: Created etc/ directory
1784--------------------- >> end captured logging << ---------------------
1785
1786======================================================================
1787ERROR: test_prepare_extracted_buildout_gp_vcsdevelop_develop_dir (anybox.recipe.odoo.tests.test_extract.TestExtraction)
1788----------------------------------------------------------------------
1789Traceback (most recent call last):
1790  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/tests/test_extract.py", line 115, in test_prepare_extracted_buildout_gp_vcsdevelop_develop_dir
1791    self.recipe._prepare_extracted_buildout(conf, self.extract_target_dir)
1792  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1446, in _prepare_extracted_buildout
1793    for raw, target, sub_dir, abs_path in self._get_gp_vcs_develops():
1794  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1165, in _get_gp_vcs_develops
1795    target = parse_egg_dir(raw)
1796  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1161, in parse_egg_dir
1797    return ireq.editable_options['egg']
1798AttributeError: 'InstallRequirement' object has no attribute 'editable_options'
1799-------------------- >> begin captured logging << --------------------
1800anybox.recipe.odoo.base: INFO: Created downloads/ directory
1801anybox.recipe.odoo.base: INFO: Created etc/ directory
1802--------------------- >> end captured logging << ---------------------
1803
1804======================================================================
1805ERROR: test_prepare_frozen_buildout_gp_vcsdevelop (anybox.recipe.odoo.tests.test_freeze.TestFreeze)
1806----------------------------------------------------------------------
1807Traceback (most recent call last):
1808  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/tests/test_freeze.py", line 145, in test_prepare_frozen_buildout_gp_vcsdevelop
1809    self.recipe._prepare_frozen_buildout(conf)
1810  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1179, in _prepare_frozen_buildout
1811    for raw, _, _, abs_path in self._get_gp_vcs_develops():
1812  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1165, in _get_gp_vcs_develops
1813    target = parse_egg_dir(raw)
1814  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1161, in parse_egg_dir
1815    return ireq.editable_options['egg']
1816AttributeError: 'InstallRequirement' object has no attribute 'editable_options'
1817-------------------- >> begin captured logging << --------------------
1818anybox.recipe.odoo.base: INFO: Created downloads/ directory
1819anybox.recipe.odoo.base: INFO: Created etc/ directory
1820--------------------- >> end captured logging << ---------------------
1821
1822======================================================================
1823ERROR: Test that prepare_frozen_buildout understands existing pinning.
1824----------------------------------------------------------------------
1825Traceback (most recent call last):
1826  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/tests/test_freeze.py", line 164, in test_prepare_frozen_buildout_gp_vcsdevelop_already_fixed
1827    self.recipe._prepare_frozen_buildout(conf)
1828  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1179, in _prepare_frozen_buildout
1829    for raw, _, _, abs_path in self._get_gp_vcs_develops():
1830  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1165, in _get_gp_vcs_develops
1831    target = parse_egg_dir(raw)
1832  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1161, in parse_egg_dir
1833    return ireq.editable_options['egg']
1834AttributeError: 'InstallRequirement' object has no attribute 'editable_options'
1835-------------------- >> begin captured logging << --------------------
1836anybox.recipe.odoo.base: INFO: Created downloads/ directory
1837anybox.recipe.odoo.base: INFO: Created etc/ directory
1838--------------------- >> end captured logging << ---------------------
1839
1840----------------------------------------------------------------------
1841Ran 199 tests in 68.713s
1842
1843FAILED (errors=4) 
```

**Comment by lmignon** [comment]
editable_options has been removed from pip
https://github.com/pypa/pip/commit/f3ca1b973f3fc64f61cfbd170806bb9c865c0dcd

On Thu, Apr 7, 2016 at 2:48 PM, Pierre Verkest <notifications@github.com>
wrote:

> Currently Anybox is migrate to buildbot 9 (public access is not yet
> available)
>
> I wonder if there is a matter with the setting of our worker(slave) or a
> real issue. I open an issue to let some analysis:
>
> Test failled on wheezy with:
>
> xcpubslave:~/buildbot.anybox.fr/a_r_odoo-py2_7/build$ bin/pip --version
> pip 1.1 from /srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/lib/python2.7/site-packages/pip-1.1-py2.7.egg (python 2.7)
>
> and passed on Jessie with:
>
> jessiepubslave:~/buildbot.anybox.fr/a_r_odoo-py2_7/build$ bin/pip --version
> pip 1.5.6 from /srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/local/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg (python 2.7)
>
> log output:
>
> ======================================================================
> 1769ERROR: test_prepare_extracted_buildout_gp_vcsdevelop (anybox.recipe.odoo.tests.test_extract.TestExtraction)
> 1770----------------------------------------------------------------------
> 1771Traceback (most recent call last):
> 1772  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/tests/test_extract.py", line 91, in test_prepare_extracted_buildout_gp_vcsdevelop
> 1773    self.recipe._prepare_extracted_buildout(conf, self.extract_target_dir)
> 1774  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1446, in _prepare_extracted_buildout
> 1775    for raw, target, sub_dir, abs_path in self._get_gp_vcs_develops():
> 1776  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1165, in _get_gp_vcs_develops
> 1777    target = parse_egg_dir(raw)
> 1778  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1161, in parse_egg_dir
> 1779    return ireq.editable_options['egg']
> 1780AttributeError: 'InstallRequirement' object has no attribute 'editable_options'
> 1781-------------------- >> begin captured logging << --------------------
> 1782anybox.recipe.odoo.base: INFO: Created downloads/ directory
> 1783anybox.recipe.odoo.base: INFO: Created etc/ directory
> 1784--------------------- >> end captured logging << ---------------------
> 1785
> 1786======================================================================
> 1787ERROR: test_prepare_extracted_buildout_gp_vcsdevelop_develop_dir (anybox.recipe.odoo.tests.test_extract.TestExtraction)
> 1788----------------------------------------------------------------------
> 1789Traceback (most recent call last):
> 1790  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/tests/test_extract.py", line 115, in test_prepare_extracted_buildout_gp_vcsdevelop_develop_dir
> 1791    self.recipe._prepare_extracted_buildout(conf, self.extract_target_dir)
> 1792  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1446, in _prepare_extracted_buildout
> 1793    for raw, target, sub_dir, abs_path in self._get_gp_vcs_develops():
> 1794  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1165, in _get_gp_vcs_develops
> 1795    target = parse_egg_dir(raw)
> 1796  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1161, in parse_egg_dir
> 1797    return ireq.editable_options['egg']
> 1798AttributeError: 'InstallRequirement' object has no attribute 'editable_options'
> 1799-------------------- >> begin captured logging << --------------------
> 1800anybox.recipe.odoo.base: INFO: Created downloads/ directory
> 1801anybox.recipe.odoo.base: INFO: Created etc/ directory
> 1802--------------------- >> end captured logging << ---------------------
> 1803
> 1804======================================================================
> 1805ERROR: test_prepare_frozen_buildout_gp_vcsdevelop (anybox.recipe.odoo.tests.test_freeze.TestFreeze)
> 1806----------------------------------------------------------------------
> 1807Traceback (most recent call last):
> 1808  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/tests/test_freeze.py", line 145, in test_prepare_frozen_buildout_gp_vcsdevelop
> 1809    self.recipe._prepare_frozen_buildout(conf)
> 1810  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1179, in _prepare_frozen_buildout
> 1811    for raw, _, _, abs_path in self._get_gp_vcs_develops():
> 1812  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1165, in _get_gp_vcs_develops
> 1813    target = parse_egg_dir(raw)
> 1814  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1161, in parse_egg_dir
> 1815    return ireq.editable_options['egg']
> 1816AttributeError: 'InstallRequirement' object has no attribute 'editable_options'
> 1817-------------------- >> begin captured logging << --------------------
> 1818anybox.recipe.odoo.base: INFO: Created downloads/ directory
> 1819anybox.recipe.odoo.base: INFO: Created etc/ directory
> 1820--------------------- >> end captured logging << ---------------------
> 1821
> 1822======================================================================
> 1823ERROR: Test that prepare_frozen_buildout understands existing pinning.
> 1824----------------------------------------------------------------------
> 1825Traceback (most recent call last):
> 1826  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/tests/test_freeze.py", line 164, in test_prepare_frozen_buildout_gp_vcsdevelop_already_fixed
> 1827    self.recipe._prepare_frozen_buildout(conf)
> 1828  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1179, in _prepare_frozen_buildout
> 1829    for raw, _, _, abs_path in self._get_gp_vcs_develops():
> 1830  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1165, in _get_gp_vcs_develops
> 1831    target = parse_egg_dir(raw)
> 1832  File "/srv/buildslave/buildbot.anybox.fr/a_r_odoo-py2_7/build/src/anybox/recipe/odoo/base.py", line 1161, in parse_egg_dir
> 1833    return ireq.editable_options['egg']
> 1834AttributeError: 'InstallRequirement' object has no attribute 'editable_options'
> 1835-------------------- >> begin captured logging << --------------------
> 1836anybox.recipe.odoo.base: INFO: Created downloads/ directory
> 1837anybox.recipe.odoo.base: INFO: Created etc/ directory
> 1838--------------------- >> end captured logging << ---------------------
> 1839
> 1840----------------------------------------------------------------------
> 1841Ran 199 tests in 68.713s
> 1842
> 1843FAILED (errors=4)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/anybox/anybox.recipe.odoo/issues/72>
>



-- 
*Laurent Mignon*
Senior software engineer

Tel: +352 20 21 10 20 32
Fax: +352 20 21 10 21
Email: laurent.mignon@acsone.eu

Acsone SA, Succursale de Luxembourg
22, Zone Industrielle
​ ​
​| L-8287 Kehlen, Luxembourg
TVA LU24733605
​ | ​RCS B160400​

​
Acsone sa/nv
Boulevard de la Woluwe 56, b4  Woluwedal
​ | B-1200 Bruxelles - Brussel
RPM Bruxelles 0835.207.216 RPR Brussel

www.acsone.eu
